### ISSUE TITLE
Refresh not working?

### ISSUE THREAD

**Issue by robertklep** [xraver/mercedes_me_api#3]
When I try to refresh a token, this is returned:
```
{"error_description":"unknown, invalid, or expired refresh token","error":"invalid_grant"}
```

Reason I was trying to manually refresh is that the access token stopped working in HA ("The redirect_uri differs from the registered one").

I retrieved a new access token and everything is working fine again, but I assume it will break again when it's time to refresh the token.

**Comment by xraver** [comment]
Hi,
thanks for the feedback. I'll check and fix it!

**Comment by xraver** [comment]
Dear.
I've found the issue.
Unfortunately the issue was related to the error message.

now i've fixed the error messages: 1 list of error messages related to creation token, 1 list related to renew token.
the error messages associated to the code 400 for refreshing token is: The given refresh token is not valid or was already used.
this means that in this case the refreshing code is expired.

If you don't refresh often the token also the refreshing code expires and lead to the user to request a new one.
thanks for this feedback!

**Comment by robertklep** [comment]
@xraver thanks! Do I understand correctly that I have to manually refresh the token periodically (using the shell script, I presume)? I was hoping that the custom HA component would do that 🥴

**Comment by xraver** [comment]
It will do. But if you don't refresh the token often it expires.
Every time you start the tool ti refresh the token.


Il Mar 15 Dic 2020, 19:48 Robert Klep <notifications@github.com> ha scritto:

**Comment by xraver** [comment]
Sorry. It does... not it will do :)

Il Mar 15 Dic 2020, 20:37 Giorgio Ravera <giorgio.ravera@gmail.com> ha
scritto:

**Comment by OlafStelter** [comment]
Dear all,
we have solved some existing issues on our end affecting the refresh token. It should work well now and the refresh token validity should be 30 days.
Best Wishes,
Olaf from Mercedes-Benz /developers

**Comment by robertklep** [comment]
Thanks @OlafStelter!

**Comment by xraver** [comment]
Thank you!
Very appreciated.

Il Mer 16 Dic 2020, 10:06 Olaf Stelter <notifications@github.com> ha
scritto:
